// <auto-generated />
using System;
using BookDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookDB.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20260312120940_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("BookDB.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 1,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 61800m,
                            Publisher = "NXB Trẻ",
                            Rating = 4.8m,
                            Title = "Cho Tôi Xin Một Vé Đi Tuổi Thơ",
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            Author = "Yuval Noah Harari",
                            CategoryId = 3,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 189000m,
                            Publisher = "NXB Văn học",
                            Rating = 4.9m,
                            Title = "Sapiens: Lược Sử Loài Người",
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            Author = "Dale Carnegie",
                            CategoryId = 4,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 86000m,
                            Publisher = "NXB Tổng hợp TP.HCM",
                            Rating = 4.7m,
                            Title = "Đắc Nhân Tâm",
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            Author = "Halliday & Resnick",
                            CategoryId = 2,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 250000m,
                            Publisher = "NXB Giáo dục",
                            Rating = 4.5m,
                            Title = "Vật Lý Đại Cương",
                            Year = 2019
                        },
                        new
                        {
                            Id = 5,
                            Author = "Robert C. Martin",
                            CategoryId = 5,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 320000m,
                            Publisher = "Prentice Hall",
                            Rating = 4.9m,
                            Title = "Clean Code",
                            Year = 2021
                        },
                        new
                        {
                            Id = 6,
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 1,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 75000m,
                            Publisher = "NXB Trẻ",
                            Rating = 4.8m,
                            Title = "Tôi Thấy Hoa Vàng Trên Cỏ Xanh",
                            Year = 2017
                        },
                        new
                        {
                            Id = 7,
                            Author = "Trần Trọng Kim",
                            CategoryId = 3,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 150000m,
                            Publisher = "NXB Văn học",
                            Rating = 4.6m,
                            Title = "Lịch Sử Việt Nam",
                            Year = 2016
                        },
                        new
                        {
                            Id = 8,
                            Author = "N. Gregory Mankiw",
                            CategoryId = 4,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 180000m,
                            Publisher = "NXB Thống kê",
                            Rating = 4.4m,
                            Title = "Kinh Tế Học Vi Mô",
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            Author = "Thomas H. Cormen",
                            CategoryId = 5,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 450000m,
                            Publisher = "MIT Press",
                            Rating = 5.0m,
                            Title = "Introduction to Algorithms",
                            Year = 2022
                        },
                        new
                        {
                            Id = 10,
                            Author = "Paula Yurkanis Bruice",
                            CategoryId = 2,
                            ImageUrl = "https://salt.tikicdn.com/cache/w1200/ts/product/5e/18/24/2a6154ba08df6ce6161c13f4303fa19e.jpg",
                            Price = 280000m,
                            Publisher = "NXB Giáo dục",
                            Rating = 4.3m,
                            Title = "Hóa Học Hữu Cơ",
                            Year = 2019
                        });
                });

            modelBuilder.Entity("BookDB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Văn học"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Khoa học"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lịch sử"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kinh tế"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Công nghệ"
                        });
                });

            modelBuilder.Entity("BookDB.Models.Book", b =>
                {
                    b.HasOne("BookDB.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookDB.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
