// <auto-generated />
using System;
using BookDB.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookDB.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20260312113918_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookDB.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            CategoryId = 1,
                            ImageUrl = "https://covers.openlibrary.org/b/id/7222246-L.jpg",
                            Price = 12.99m,
                            Publisher = "Scribner",
                            Rating = 4.5m,
                            Title = "The Great Gatsby",
                            Year = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CategoryId = 1,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8228691-L.jpg",
                            Price = 14.99m,
                            Publisher = "J.B. Lippincott & Co.",
                            Rating = 4.8m,
                            Title = "To Kill a Mockingbird",
                            Year = 1960
                        },
                        new
                        {
                            Id = 3,
                            Author = "George Orwell",
                            CategoryId = 1,
                            ImageUrl = "https://covers.openlibrary.org/b/id/7222246-L.jpg",
                            Price = 13.99m,
                            Publisher = "Secker & Warburg",
                            Rating = 4.7m,
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            CategoryId = 1,
                            Price = 11.99m,
                            Publisher = "T. Egerton",
                            Rating = 4.6m,
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "Stephen Hawking",
                            CategoryId = 2,
                            ImageUrl = "https://covers.openlibrary.org/b/id/9255566-L.jpg",
                            Price = 18.99m,
                            Publisher = "Bantam Books",
                            Rating = 4.4m,
                            Title = "A Brief History of Time",
                            Year = 1988
                        },
                        new
                        {
                            Id = 6,
                            Author = "Richard Dawkins",
                            CategoryId = 2,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 16.99m,
                            Publisher = "Oxford University Press",
                            Rating = 4.3m,
                            Title = "The Selfish Gene",
                            Year = 1976
                        },
                        new
                        {
                            Id = 7,
                            Author = "Carl Sagan",
                            CategoryId = 2,
                            Price = 19.99m,
                            Publisher = "Random House",
                            Rating = 4.9m,
                            Title = "Cosmos",
                            Year = 1980
                        },
                        new
                        {
                            Id = 8,
                            Author = "Yuval Noah Harari",
                            CategoryId = 3,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 22.99m,
                            Publisher = "Harper",
                            Rating = 4.7m,
                            Title = "Sapiens: A Brief History of Humankind",
                            Year = 2011
                        },
                        new
                        {
                            Id = 9,
                            Author = "Jared Diamond",
                            CategoryId = 3,
                            Price = 20.99m,
                            Publisher = "W. W. Norton & Company",
                            Rating = 4.5m,
                            Title = "Guns, Germs, and Steel",
                            Year = 1997
                        },
                        new
                        {
                            Id = 10,
                            Author = "Peter Frankopan",
                            CategoryId = 3,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 21.99m,
                            Publisher = "Bloomsbury",
                            Rating = 4.4m,
                            Title = "The Silk Roads",
                            Year = 2015
                        },
                        new
                        {
                            Id = 11,
                            Author = "Walter Isaacson",
                            CategoryId = 4,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 24.99m,
                            Publisher = "Simon & Schuster",
                            Rating = 4.6m,
                            Title = "The Innovators",
                            Year = 2014
                        },
                        new
                        {
                            Id = 12,
                            Author = "Robert C. Martin",
                            CategoryId = 4,
                            Price = 44.99m,
                            Publisher = "Prentice Hall",
                            Rating = 4.8m,
                            Title = "Clean Code",
                            Year = 2008
                        },
                        new
                        {
                            Id = 13,
                            Author = "Andrew Hunt and David Thomas",
                            CategoryId = 4,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 39.99m,
                            Publisher = "Addison-Wesley",
                            Rating = 4.7m,
                            Title = "The Pragmatic Programmer",
                            Year = 1999
                        },
                        new
                        {
                            Id = 14,
                            Author = "Walter Isaacson",
                            CategoryId = 5,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 19.99m,
                            Publisher = "Simon & Schuster",
                            Rating = 4.5m,
                            Title = "Steve Jobs",
                            Year = 2011
                        },
                        new
                        {
                            Id = 15,
                            Author = "Anne Frank",
                            CategoryId = 5,
                            Price = 12.99m,
                            Publisher = "Contact Publishing",
                            Rating = 4.9m,
                            Title = "The Diary of a Young Girl",
                            Year = 1947
                        },
                        new
                        {
                            Id = 16,
                            Author = "Nelson Mandela",
                            CategoryId = 5,
                            ImageUrl = "https://covers.openlibrary.org/b/id/8231986-L.jpg",
                            Price = 17.99m,
                            Publisher = "Little, Brown and Company",
                            Rating = 4.8m,
                            Title = "Long Walk to Freedom",
                            Year = 1994
                        });
                });

            modelBuilder.Entity("BookDB.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fiction"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 3,
                            Name = "History"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Technology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Biography"
                        });
                });

            modelBuilder.Entity("BookDB.Models.Book", b =>
                {
                    b.HasOne("BookDB.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BookDB.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
